<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>eed602e0-4223-496d-b1f7-f160022f4b57</testSuiteGuid>
   <testCaseLink>
      <guid>dd104e2f-b046-488c-96e7-f72ae00f5ad6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TestCase_Login</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>7b1a5328-866b-4127-bb25-fb39fb652c78</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login_Field</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7b1a5328-866b-4127-bb25-fb39fb652c78</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>f7d89cf5-fe83-492d-80b2-370ae3d8ed37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7b1a5328-866b-4127-bb25-fb39fb652c78</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>0054a483-f5e9-4a7a-b51c-b7d8c774ac20</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
